/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2016-03-25 20:06:55 UTC)
 * on 2016-04-02 at 07:02:39 UTC 
 * Modify at your own risk.
 */

package com.appspot.kavachhq.hudapi;

/**
 * Service definition for Hudapi (v1).
 *
 * <p>
 * An API to manage HUD Messages Info
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link HudapiRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Hudapi extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the hudapi library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://kavachhq.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "hudapi/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Hudapi(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Hudapi(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the HudapiOperations collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Hudapi hudapi = new Hudapi(...);}
   *   {@code Hudapi.HudapiOperations.List request = hudapi.hudapi().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public HudapiOperations hudapi() {
    return new HudapiOperations();
  }

  /**
   * The "hudapi" collection of methods.
   */
  public class HudapiOperations {

    /**
     * Create a request for the method "hudapi.addmessage".
     *
     * This request holds the parameters needed by the hudapi server.  After setting any optional
     * parameters, call the {@link Addmessage#execute()} method to invoke the remote operation.
     *
     * @param aid
     * @param content
     * @param meantfor
     * @return the request
     */
    public Addmessage addmessage(java.lang.String aid, java.lang.String content, java.lang.String meantfor) throws java.io.IOException {
      Addmessage result = new Addmessage(aid, content, meantfor);
      initialize(result);
      return result;
    }

    public class Addmessage extends HudapiRequest<com.appspot.kavachhq.hudapi.model.Container> {

      private static final String REST_PATH = "putHUDThing/{aid}/{content}/{meantfor}";

      /**
       * Create a request for the method "hudapi.addmessage".
       *
       * This request holds the parameters needed by the the hudapi server.  After setting any optional
       * parameters, call the {@link Addmessage#execute()} method to invoke the remote operation. <p>
       * {@link
       * Addmessage#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param aid
       * @param content
       * @param meantfor
       * @since 1.13
       */
      protected Addmessage(java.lang.String aid, java.lang.String content, java.lang.String meantfor) {
        super(Hudapi.this, "POST", REST_PATH, null, com.appspot.kavachhq.hudapi.model.Container.class);
        this.aid = com.google.api.client.util.Preconditions.checkNotNull(aid, "Required parameter aid must be specified.");
        this.content = com.google.api.client.util.Preconditions.checkNotNull(content, "Required parameter content must be specified.");
        this.meantfor = com.google.api.client.util.Preconditions.checkNotNull(meantfor, "Required parameter meantfor must be specified.");
      }

      @Override
      public Addmessage setAlt(java.lang.String alt) {
        return (Addmessage) super.setAlt(alt);
      }

      @Override
      public Addmessage setFields(java.lang.String fields) {
        return (Addmessage) super.setFields(fields);
      }

      @Override
      public Addmessage setKey(java.lang.String key) {
        return (Addmessage) super.setKey(key);
      }

      @Override
      public Addmessage setOauthToken(java.lang.String oauthToken) {
        return (Addmessage) super.setOauthToken(oauthToken);
      }

      @Override
      public Addmessage setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Addmessage) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Addmessage setQuotaUser(java.lang.String quotaUser) {
        return (Addmessage) super.setQuotaUser(quotaUser);
      }

      @Override
      public Addmessage setUserIp(java.lang.String userIp) {
        return (Addmessage) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String aid;

      /**

       */
      public java.lang.String getAid() {
        return aid;
      }

      public Addmessage setAid(java.lang.String aid) {
        this.aid = aid;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.String content;

      /**

       */
      public java.lang.String getContent() {
        return content;
      }

      public Addmessage setContent(java.lang.String content) {
        this.content = content;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.String meantfor;

      /**

       */
      public java.lang.String getMeantfor() {
        return meantfor;
      }

      public Addmessage setMeantfor(java.lang.String meantfor) {
        this.meantfor = meantfor;
        return this;
      }

      @Override
      public Addmessage set(String parameterName, Object value) {
        return (Addmessage) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "hudapi.getmessages".
     *
     * This request holds the parameters needed by the hudapi server.  After setting any optional
     * parameters, call the {@link Getmessages#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public Getmessages getmessages() throws java.io.IOException {
      Getmessages result = new Getmessages();
      initialize(result);
      return result;
    }

    public class Getmessages extends HudapiRequest<com.appspot.kavachhq.hudapi.model.Container> {

      private static final String REST_PATH = "container";

      /**
       * Create a request for the method "hudapi.getmessages".
       *
       * This request holds the parameters needed by the the hudapi server.  After setting any optional
       * parameters, call the {@link Getmessages#execute()} method to invoke the remote operation. <p>
       * {@link
       * Getmessages#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected Getmessages() {
        super(Hudapi.this, "GET", REST_PATH, null, com.appspot.kavachhq.hudapi.model.Container.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Getmessages setAlt(java.lang.String alt) {
        return (Getmessages) super.setAlt(alt);
      }

      @Override
      public Getmessages setFields(java.lang.String fields) {
        return (Getmessages) super.setFields(fields);
      }

      @Override
      public Getmessages setKey(java.lang.String key) {
        return (Getmessages) super.setKey(key);
      }

      @Override
      public Getmessages setOauthToken(java.lang.String oauthToken) {
        return (Getmessages) super.setOauthToken(oauthToken);
      }

      @Override
      public Getmessages setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Getmessages) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Getmessages setQuotaUser(java.lang.String quotaUser) {
        return (Getmessages) super.setQuotaUser(quotaUser);
      }

      @Override
      public Getmessages setUserIp(java.lang.String userIp) {
        return (Getmessages) super.setUserIp(userIp);
      }

      @Override
      public Getmessages set(String parameterName, Object value) {
        return (Getmessages) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Hudapi}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Hudapi}. */
    @Override
    public Hudapi build() {
      return new Hudapi(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link HudapiRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setHudapiRequestInitializer(
        HudapiRequestInitializer hudapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(hudapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
